import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/homepage/Navbar/Navbar";
import Footer from "@/components/homepage/Footer/Footer";


export const metadata: Metadata = {
  title: "Uzzal Motors | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}