import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css"
import DashboardMenu from "@/components/dashboard/DashboardMenu/DashboardMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardMenu>
          {children}
        </DashboardMenu>
      </body>
    </html>
  );
}
